Attempt to Fix MSVC build
.\tutorial.cpp(246): warning C4003: not enough arguments for function-like macro invocation 'W_MACRO_STRREMSCOPE'
41.\tutorial.cpp(246): error C2672: 'w_internal::removedScopeSize': no matching overloaded function found
42.\tutorial.cpp(246): error C2780: 'int w_internal::removedScopeSize(const char (&)[N])': expects 1 arguments - 0 provided